apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockserver-pod
  template:
    metadata:
      labels:
        app: mockserver-pod
    spec:
      containers:
      - name: mockserver-container
        image: ghcr.io/satyanarayana-senapathi/bootcamp105-mockserver:latest
        ports:
        - containerPort: 3001
      
      imagePullSecrets:
      - name: my-ghcr-secret