name: BOOTCAMP105 - BACKEND deployment 
run-name: Backend deployment update triggered by ${{ github.actor }}.
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yaml'
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: backend
    strategy:
        matrix:
            services:
            - service-registry
            - api-gateway
            - business-service
            - cloud-config-server
            - transaction-service
            - user-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' 
          java-version: '11'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ secrets.GHCR_USERNAME }}
         password: ${{ secrets.GHCR_PAT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: adding eks-cluster
        env: 
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
        run: |
            aws eks --region $aws_region update-kubeconfig --name $cluster_name
      - name: Run Strategy
        run: |
            cd ${{ matrix.services }}
            mvn clean package -DskipTests 
            docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp105-backend-${{ matrix.services }}:v${{ github.run_number }} .
            docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp105-backend-${{ matrix.services }}:v${{ github.run_number }}
            kubectl set image deployment/${{ matrix.services }}-deployment ${{ matrix.services }}-container=ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp105-backend-${{ matrix.services }}:v${{ github.run_number }}
 
      
            
